packages:
    - 'apps/*'
    - 'packages/*'
    - 'tooling/*'

catalog:
    'prettier': '^3.7.4'
    'eslint': '^10.0.2'
    '@types/node': '^25.3.3'
    'typescript': '5.9.2'

publicHoistPattern:
    - '@ianvs/prettier-plugin-sort-imports'
    - prettier-plugin-tailwindcss
